apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: k8s-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa
      containers:
        - name: backend
          image: ghcr.io/mickeyreg/k8s_test_app-backend:sha-269ae6c189976a0b70d3c39ba0ba5080c896aa25
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /api
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
